ServerlessController/MSc_Research_Django/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('provider/', include('providers_app.urls')),
    path('developers/', include('developers_app.urls')),
    path('profiles/', include('profiles.urls')),
    path('controller/', include('controller_app.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index')
]

ServerlessController/developers_app/urls.py
from django.urls import path

from . import views

app_name = 'developers_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('new_service/', views.new_service, name='new_service'),
    path('user_services/', views.user_services, name='user_services'),
    path('user_jobs/', views.user_jobs, name='user_jobs'),
    path('<int:service_id>/stop_service/', views.stop_service, name='stop_service'),
    path('<int:service_id>/start_service/', views.start_service, name='start_service'),
    path('<int:service_id>/delete_service/', views.delete_service, name='delete_service'),
    path('<int:service_id>/run/', views.run_service, name='run_service'),
    path('<int:service_id>/run_async/', views.run_service_async, name='run_service_async'),
    path('<int:job_id>/job_info/', views.job_info, name='job_info'),
]

ServerlessController/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('change_info/', views.change_info, name='change_info'),
    path('delete_test_users/', views.delete_test_users, name='delete_test_users'),
]

ServerlessController/providers_app/urls.py
from django.urls import path

from . import views

app_name = 'providers_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('stop/', views.stop_providing, name='stop_providing'),
    path('ready/', views.ready, name='ready'),
    path('not_ready/', views.not_ready, name='not_ready'),
    path('job_ack/', views.job_ack, name='job_ack'),
]

ServerlessController/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ChainFaaS</title>
    <!-- Latest compiled and minified CSS -->
    {% bootstrap_css %}
    {#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"#}
    {#          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">#}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" type="text/css" href="/static/MSc_Research_Django/css/style.css">
</head>
<body>
{#<nav class="navbar navbar-default navbar-static-top">#}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">ChainFaaS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">

        <div class="container">
            <ul class="navbar-nav">
                <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li> -->

                {% if user.is_authenticated %}
                    {% if user.provider.active %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'providers_app:index' %}">Provider</a>
                    </li>
                    {% endif %}

                    {% if user.developer.active %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Developer
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'developers_app:new_service' %}">New Function</a>
                            <a class="dropdown-item" href="{% url 'developers_app:user_services' %}">Your Functions</a>
                            <a class="dropdown-item" href="{% url 'developers_app:user_jobs' %}">Your Jobs</a>
                        </div>
                    </li>
                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profiles:user_logout' %}">Logout</a>
                    </li>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profiles:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profiles:user_login' %}">Login</a>
                    </li>
                    
                {% endif %}

                <li class="nav-item">
                    <a class="nav-link"  target="_blank" href="https://chainfaas.readthedocs.io/">Docs</a>
                </li>
            </ul>
        </div>
    </div>

</nav>
<div class="container background-container">
    {#    {% bootstrap_messages %}#}
    {% if messages %}
        <div class="container">
            {% for message in messages %}

                <div class="{{ message|bootstrap_message_classes }} alert-dismissable direction-rtl align-right">
                    {{ message }}
                    <button type="button" class="close message-button pull-right" data-dismiss="alert"
                            aria-hidden="true">&#215;
                    </button>
                </div>
            {% endfor %}
        </div>
    {% endif %}
    {% block body_block %}
    {% endblock %}
</div>

<footer>
    <div class="row">
      <div class="mx-auto mb-4 index-footer" >
          <span>© Copyright <a href="https://pacs.eecs.yorku.ca/">PACS Lab</a> 2020.</span>
      </div>
    </div>
  </footer>
</body>
</html>

ServerlessController/templates/final_response.html
{% extends "base.html" %}
{% block body_block %}

    <div class="container">
        <div class="jumbotron">
            <h1>Response</h1>
            <p> This request was handled by {{ provider }} and the job ID is {{job_id}}. </p>
            <!-- <p> This request was handled by {{ provider }}. It took {{ pull_time | floatformat:-4 }} milliseconds to pull the
                docker image from registry and {{ run_time | floatformat:-4 }} milliseconds to run it. {{ total_time }}, {{providing_time}}</p> -->
            <h3>Results: </h3>
                <p>
                    {{ result|linebreaks }}
                </p>
            <h3>Performance Metrics</h3>
            <p>To better understand the performance metrics shown in this page, visit <a href='https://chainfaas.readthedocs.io/en/latest/perf.html'>the docs</a>.</p>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Type</th>
                    <th>Time (ms)</th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Providing Time</td>
                        <td>{{providing_time}} </td>
                    </tr>
                    <tr>
                        <td>Pull Time</td>
                        <td>{{ pull_time }} </td>
                    </tr>
                    <tr>
                        <td>Run Time</td>
                        <td>{{ run_time }} </td>
                    </tr>
                    <tr>
                        <td>Total Time</td>
                        <td>{{ total_time }} </td>
                    </tr>
                </tbody>
            </table>
                
            
        </div>
    </div>

{% endblock %}

ServerlessController/templates/index.html
{% extends "base.html" %}
{% block body_block %}
{% load static %}

<div class="container">
  <div class="jumbotron">
    <h1>ChainFaaS</h1>
    <h4 class="mb-5">An Open Blockchain-based Serverless Platform</h4>

    <!-- <p>ChainFaaS takes advantage of personal computers to run serverless tasks. And the following are the main features of this platform: </p> -->
    <div class=container>
      <div class="row">
        <div class="col-6">
          <img src="{% static "MSc_Research_Django/img/team.png" %}" width="50" height="50">
          <h3>Public</h3>
          <p>It is public in the sense that anyone can be either a developer, provider or both. 
            Anyone with excess computational power can connect their computer to this platform. 
            Developerscan then rent from this vast pool of compute at scale. 
            A user may choose to be a provider and developer at the same time. 
          </p>
        </div>

        <div class="col-6">
          <img src="{% static "MSc_Research_Django/img/binocular.png" %}" width="50" height="50">
          <h3>Open</h3>
          <p>It is open and transparent to everyone. Anyone can observe the transactions on 
            this platform. They can verify the billing information, and check the status and history of each job. 
            Every single detail os stored and kept on the blockchain network.</p>     
        </div>
      </div>

      <div class="row">
        <div class="col-6">
          <img src="{% static "MSc_Research_Django/img/computer.png" %}" width="50" height="50">
          <h3>Use of Personal Computers </h3>
          <p>It is based on the excess computing power available on personal computers. 
            Regular computer users can rent out their unused computational power by connecting it to a large network of resources.</p>    
        </div>

        <div class="col-6">
          <img src="{% static "MSc_Research_Django/img/price.png" %}" width="50" height="50">
          <h3>Affordable</h3>
          <p>It is affordable for developers, especially compared to similar centralized (in terms of management) cloud solutions.
             Given that the functions run on personal computer and there is no server maintenace costs, this platform is cheaper that other serverless solutions. </p>    
        </div>
      </div>

      <div class="row">
        <div class="col-6">
          <img src="{% static "MSc_Research_Django/img/responsive.png" %}" width="50" height="50">
          <h3>Fog and Edge Computing </h3>
          <p>It embodies edge and fog computing by nature as ChainFaaS can get very close to the end-user. Since in ChainFaaS, 
            functions run on personal computers, it can be a great platform for edge and fog computing.
            Developers who need to run IoT applications closer to end-users can use this platform instead of other computing services that run on servers. </p>    
        </div>

        <div class="col-6">
          <img src="{% static "MSc_Research_Django/img/user.png" %}" width="50" height="50">
          <h3>Usability</h3>
          <p>It is user-friendly and easy to use. ChainFaaS is designed to be used by anyone. 
            Although it is a sophisticated platform based on the state of the art technology, 
            the users are not necessarily computer professionals. It is designed in such a way that anyone, 
            including users with no background in computer science, can easily become a computing provider or blockchain peer. </p>    
        </div>
      </div>
    </div>

    <!-- <p>There are three main parts to this platform: Blockchain network, serverless controller, and excecution network.</p> -->
    <p>To become a computing provider or developer in this platform, you first need to register as a new user. Go to the <a href="/profiles/register/">registration page</a> to register. </p>
  </div>

  <footer>
    <div class="row">
      <div class="mx-auto mb-4 index-footer" >
          <!-- <span>© Copyright Kards 2016.</span> -->
          <span>Icons made by <a href="https://www.flaticon.com/authors/dinosoftlabs" title="DinosoftLabs">DinosoftLabs</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a></span>
      </div>
    </div>
  </footer>

</div>



{% endblock %}