ServerlessController/MSc_Research_Django/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('provider/', include('providers_app.urls')),
    path('developers/', include('developers_app.urls')),
    path('profiles/', include('profiles.urls')),
    path('controller/', include('controller_app.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index')
]

ServerlessController/developers_app/urls.py
from django.urls import path

from . import views

app_name = 'developers_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('new_service/', views.new_service, name='new_service'),
    path('user_services/', views.user_services, name='user_services'),
    path('user_jobs/', views.user_jobs, name='user_jobs'),
    path('<int:service_id>/stop_service/', views.stop_service, name='stop_service'),
    path('<int:service_id>/start_service/', views.start_service, name='start_service'),
    path('<int:service_id>/delete_service/', views.delete_service, name='delete_service'),
    path('<int:service_id>/run/', views.run_service, name='run_service'),
    path('<int:service_id>/run_async/', views.run_service_async, name='run_service_async'),
    path('<int:job_id>/job_info/', views.job_info, name='job_info'),
]

ServerlessController/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('change_info/', views.change_info, name='change_info'),
    path('delete_test_users/', views.delete_test_users, name='delete_test_users'),
]

ServerlessController/developers_app/models.py
from django.db import models
from profiles.models import Developer, User, Provider


# Create your models here.
class Services(models.Model):
    developer = models.ForeignKey(Developer, on_delete=models.CASCADE)
    provider = models.ForeignKey(Provider, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=30)
    docker_container = models.URLField()
    active = models.BooleanField(default=False)

    class Meta:
        # Each developer can only have one service with a specific name
        unique_together = ['name', 'developer']

ServerlessController/developers_app/forms.py
from django import forms
from developers_app.models import Services


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Services
        fields = ('name', 'docker_container')

ServerlessController/developers_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from developers_app.forms import ServiceForm
from django.contrib import messages
from django.db import IntegrityError
from developers_app.models import Services
from providers_app.models import Job
from django.core.exceptions import ObjectDoesNotExist
from controller_app.views import request_handler, find_provider
from datetime import datetime
from pytz import timezone
from MSc_Research_Django.settings import TIME_ZONE
from datetime import timedelta
import json
import threading


def index(request):
    return render(request, 'developers_app/index.html')


@login_required()
def new_service(request):
    """
    Creates a new service in the network.
    """
    if request.method == 'POST':
        service_form = ServiceForm(data=request.POST)
        if service_form.is_valid():
            service = service_form.save(commit=False)
            service.developer = request.user.developer
            service.provider = None
            service.active = True
            try:
                service.save()
                messages.success(request, "New service created")
                service_form = ServiceForm()
            except IntegrityError:
                messages.error(request, "You already have a service with this name")
        else:
            print(service_form.errors)
    else:
        service_form = ServiceForm()

    return render(request, 'developers_app/new_service.html',
                  {'service_form': service_form})


@login_required()
def user_services(request):
    """
    Shows all services owned by a user.
    """
    all_services = Services.objects.filter(developer=request.user.developer)

    return render(request, 'developers_app/user_services.html',
                  {'all_services': all_services,
                   'developer_id': request.user.developer.id})

@login_required()
def stop_service(request, service_id):
    all_services = Services.objects.filter(developer=request.user.developer)
    service = Services.objects.get(id=service_id)
    service.active = False
    service.save()
    return render(request, 'developers_app/services_table.html',
                  {'all_services': all_services,
                   'developer_id': request.user.developer.id})


@login_required()
def start_service(request, service_id):
    service = Services.objects.get(id=service_id)
    all_services = Services.objects.filter(developer=request.user.developer)
    service.active = True
    service.save()
    return render(request, 'developers_app/services_table.html',
                  {'all_services': all_services,
                   'developer_id': request.user.developer.id})


@login_required()
def delete_service(request, service_id):
    all_services = Services.objects.filter(developer=request.user.developer)
    service = Services.objects.get(id=service_id)
    service.delete()
    return render(request, 'developers_app/services_table.html',
                  {'all_services': all_services,
                   'developer_id': request.user.developer.id})


def run_service(request, service_id):
    response = ''
    try:
        service = Services.objects.get(id=service_id)
        if service.active:
            temp_time = datetime.now(tz=timezone(TIME_ZONE))
            response, provider, providing_time, job_id = request_handler(request, service, temp_time)
            if response is None:
                messages.error(request, "There are no available providers in the network")
                return redirect('index')
            else:
                messages.success(request, "Successfully sent a request to '{}' service of '{}'".format(service.name,
                                                                                                   service.developer))
        else:
            messages.error(request, "This service is disabled")

    except ObjectDoesNotExist:
        messages.error(request, "Incorrect service id")

    return render(request, 'final_response.html',
                  {'result': response['Result'],
                   'providing_time': providing_time,
                   'pull_time': response['pull_time'],
                   'run_time': response['run_time'],
                   'total_time': response['total_time'],
                   'provider': provider, 
                   'job_id': job_id})
                   
def run_service_async(request, service_id):
    response = ''
    try:
        service = Services.objects.get(id=service_id)
        if service.active:
            temp_time = datetime.now(tz=timezone(TIME_ZONE))
            # request_handler(request, service, temp_time, run_async=True)
            x = threading.Thread(target=request_handler, args=(request, service, temp_time, True))
            x.start()
            if find_provider() is None:
                messages.error(request, "There are no available providers in the network")
                return redirect('index')
            else:
                messages.success(request, "Successfully sent an async request to '{}' service of '{}'".format(service.name,
                                                                                                   service.developer))
        else:
            messages.error(request, "This service is disabled")

    except ObjectDoesNotExist:
        messages.error(request, "Incorrect service id")

    return redirect('index')

@login_required()
def user_jobs(request):
    """
    Shows all jobs that belong to a user.
    """
    services = Services.objects.filter(developer=request.user.developer)
    all_jobs = Job.objects.filter(service__in=services).order_by('pk').reverse()
    return render(request, 'developers_app/user_jobs.html',
                  {'all_jobs': all_jobs,
                   'developer_id': request.user.developer.id})


@login_required()
def job_info(request, job_id):
    """
    Shows all jobs that belong to a user.
    """
    job = Job.objects.get(pk=job_id)
    providing_time = int(((job.ack_time - job.start_time)/timedelta(microseconds=1))/1000)
    if job.response == '':
        result = "Result is not ready yet."
    else:
        result = json.loads(job.response)['Result']
    return render(request, 'final_response.html',
                  {'result': result,
                   'providing_time': providing_time,
                   'pull_time': job.pull_time,
                   'run_time': job.run_time,
                   'total_time': job.total_time,
                   'provider': job.provider.user.username, 
                   'job_id': job.pk})

ServerlessController/templates/developers_app/index.html
{% extends "base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Developer Page</h1>
  </div>
</div>

{% endblock %}

ServerlessController/templates/developers_app/new_service.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}

{% block body_block %}
    <div class="container">
        <div class="jumbotron">

            <h1>Add New Function Here</h1>
            <p>As a developer, you can submit a new function to ChainFaaS by providing its docker registery public link. You can then go to <a href="/developers/user_services/">your fucntions page</a> to see the status of all your functions.</p>
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                <table>
                    {% bootstrap_form service_form %}
                </table>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>

        </div>

    </div>

{% endblock %}

ServerlessController/templates/developers_app/services_table.html
{% load staticfiles %}
{% load bootstrap4 %}


<table class="table table-hover">
    <thead>
    <tr>
        <th>Function Name</th>
        <th>URL</th>
        <th>Status</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>

    {% for service in all_services %}
        <tr>
            <td>{{ service.name }}</td>
            <td>{{ service.docker_container }}</td>
            {% if  service.active %}
                <td class="service-status" data-id="{{ service.id }}"> Active</td>
            {% else %}
                <td class="service-status" data-id="{{ service.id }}"> Disabled</td>
            {% endif %}
            <td>
                <div class="dropdown">
                    <button type="button" class="btn dropdown-toggle"
                            style="background-color: #2980b9; color:white" data-toggle="dropdown">
                        Action
                    </button>
                    <div class="dropdown-menu">
                        {% if  service.active %}
                            <a class="dropdown-item stop-btn" data-serviceid="{{ service.id }}"
                               href="{% url 'developers_app:stop_service' service.id %}">Stop
                                Function</a>
                            <a class="dropdown-item run-btn" data-serviceid="{{ service.id }}"
                               href="{% url 'developers_app:run_service' service.id %}">Send
                                a Request</a>
                            <a class="dropdown-item run-async-btn" data-serviceid="{{ service.id }}"
                            href="{% url 'developers_app:run_service_async' service.id %}">Send
                                an Async Request</a>
                        {% else %}
                            <a class="dropdown-item start-btn" data-serviceid="{{ service.id }}"
                               href="{% url 'developers_app:start_service' service.id %}">Start
                                Function</a>
                        {% endif %}

                        <a class="dropdown-item"
                           href="#" data-toggle="modal" data-target="#DeleteModal{{ service.id }}">Delete
                            Function</a>


                    </div>
                </div>
            </td>
        </tr>
        <div class="modal" id="DeleteModal{{ service.id }}">
            <div class="modal-dialog">
                <div class="modal-content">

                    <div class="modal-header">
                        <h4 class="modal-title">Are you sure?</h4>
                        <button type="button" class="close" data-dismiss="modal">
                            &times;
                        </button>
                    </div>

                    <div class="modal-body">
                        By deleting this function, you won't be able to run it on this platform anymore.
                    </div>

                    <div class="modal-footer">
                        <a class="btn btn-danger delete-btn" data-dismiss="modal" data-serviceid="{{ service.id }}" role="button"
                           href="{% url 'developers_app:delete_service' service.id %}">Delete</a>

                        <button type="button" class="btn btn-info"
                                style="background-color: #2980b9; color:white"
                                data-dismiss="modal">Close
                        </button>
                    </div>

                </div>
            </div>
        </div>
    {% endfor %}

    </tbody>
</table>

ServerlessController/templates/developers_app/user_jobs.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}

{% block body_block %}
    <div class="container">
        <div class="jumbotron">
            <h2>All Jobs</h2>
            <p>A list of all your jobs:</p>
            <div class="table-responsive" id="jobsTable">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Job ID</th>
                        <th>Function</th>
                        <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for job in all_jobs %}
                        <tr>
                            <td> <a href="{% url 'developers_app:job_info' job_id=job.id %}">Job {{ job.id }}</a>  
                            </td>
                            <td>{{ job.service.name }}</td>
                            
                            <td> 
                                {% if job.finished %}
                                    Finished
                                {% else %}
                                    Not finished
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                
                    </tbody>
                </table>
            </div>

        </div>
    </div>
{% endblock %}

ServerlessController/templates/developers_app/user_services.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}

{% block body_block %}
    <div class="container">
        <div class="jumbotron">
            <h2>All Functions</h2>
            <p>A list of all your functions:</p>
            <div class="table-responsive" id="servicesTable">
                {% include "developers_app/services_table.html" %}
            </div>

        </div>
    </div>

    <script>
        updateService = function (idx) {
            $(this).click(function (event) {
                event.preventDefault()
                $.ajax({
                    url: $(this).attr('href')
                }).done(function (data) {
                    console.log(data)
                    $('#servicesTable').html(data)

                    $('.stop-btn').each(updateService)
                    $('.start-btn').each(updateService)
                    $('.delete-btn').each(updateService)
                });
            })
        }

        // runService = function (idx) {
        //     $(this).click(function (event) {
        //         {#event.preventDefault()#}
        //         $.ajax({
        //             url: $(this).attr('href')
        //         }).done(function (data) {
        //             $('.run-btn').each(runService)
        //         });
        //     })
        // }

        $('.stop-btn').each(updateService)
        $('.start-btn').each(updateService)
        $('.delete-btn').each(updateService)
    </script>
{% endblock %}